# Generated by Django 5.2.9 on 2025-12-27 04:50

from django.db import migrations, models


def mark_new_buildings(apps, schema_editor):

    Flat: models.Model = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gr=2014).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(mark_new_buildings)
    ]
