# Generated by Django 5.2.9 on 2025-12-27 04:50

from django.db import migrations, models


def mark_new_buildings(apps, schema_editor):

    Flat: models.Model = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year > 2014
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(mark_new_buildings)
    ]
