# Generated by Django 5.2.9 on 2026-01-14 10:39

from django.db import migrations, models
from phonenumbers import (
    is_valid_number,
    parse,
    format_number,
    PhoneNumberFormat
)


def parse_numbers(apps, schema_editor):
    Flat: models.Model = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phone_number = parse(flat.owners_phonenumber, 'RU')
        if is_valid_number(parsed_phone_number):
            flat.owners_pure_phonenumber = format_number(
                parsed_phone_number,
                PhoneNumberFormat.E164
            )
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owners_pure_phonenumber'),
    ]

    operations = [
        migrations.RunPython(parse_numbers),
    ]
