# Generated by Django 5.2.9 on 2026-01-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20260114_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner',
            new_name='deprecated_owner',
        ),
    ]
