# Generated by Django 5.2.9 on 2026-01-15 06:36

from django.db import migrations, models
from property import models


def migrate_owners(apps, schema_editor):
    Flat: models.Model = apps.get_model('property', 'Flat')
    Owner: models.Model = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            name=flat.deprecated_owner,
            phonenumber=flat.owners_phonenumber,
            pure_phonenumber=flat.owners_pure_phonenumber
        )

        if not owner.flats.contains(flat):
            owner.flats.add(flat)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_owners),
    ]
