# Generated by Django 5.2.9 on 2026-01-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20260115_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='deprecated_owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_pure_phonenumber',
        ),
    ]
