# Generated by Django 5.2.9 on 2026-01-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_remove_flat_deprecated_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='owned_by', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
