# Generated by Django 5.2.9 on 2026-01-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_owner_flats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(db_index=True, default=False, null=True, verbose_name='Новостройка'),
        ),
    ]
