# Generated by Django 5.2.9 on 2026-01-21 04:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_owner_flats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complain',
            new_name='Complaint',
        ),
    ]
